### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by CraigglesO** [keepkey/device-client#2]
While I had no issues with python getting the keepkey to do my bidding, I have little experience in Typescript. I can build the package fine with `tsc` but the device-client-manager requires `hidHelper` and `rawFirmwareStreamFactory` to be set before actively seeking devices and connecting to them successfully. Would you mind just giving connection example?

**Comment by bgok** [comment]
Both of these abstract away the differences between how chrome and node work.

I removed the requirement for providing a rawFirmwareStreamFactory until the firmware-upload-action is called, so unless your plan to implement a device client that can update firmware, this won't be required. Here is an example of the one from the KeepKey Chrome client:

````typescript
export class FirmwareStreamReadable extends Readable {
  public static factory(): FirmwareStreamReadable {
    let firmwareData = require('@keepkey/device-client/dist/keepkey_main.json');

    return new FirmwareStreamReadable(firmwareData.file, {
      highWaterMark: 500000,
      objectMode: false
    });
  }

  private httpRequest: XMLHttpRequest;
  private reading: boolean = false;

  constructor(private fileName: string, options: ReadableOptions) {
    super(options);
  }

  private go(size: number) {
    this.httpRequest = new XMLHttpRequest();

    this.httpRequest.addEventListener('loadend', () => {
      this.push(Buffer.from(this.httpRequest.response));
      this.push(null);
    });

    this.httpRequest.open('GET', this.fileName, true);
    this.httpRequest.responseType = 'arraybuffer';
    this.httpRequest.send();
  }

  public _read(size: number) {
    if (!this.reading) {
      this.reading = true;
      this.go(size);
    }
  }
}
````


The purpose of hidHelper is to provide a common way of determining the active HID device. Here is how it works for chrome:

````typescript
export class ChromeHidHelper implements HidHelper {
  public getActiveClient() {
    return this.getActiveDeviceId()
      .then((device: any) => {
        if (device) {
          var client = DeviceClientManager.instance.findByDeviceId(device.deviceId);
          if (!client) {
            return new Promise((resolve) => {
              ChromeHidTransport.factory(device, (newClient) => {
                resolve(newClient);
              });
            });
          } else {
            return Promise.resolve(client);
          }
        } else {
          Promise.reject('No device found. This should not happen.');
        }
      });
  }

  private getActiveDeviceId() {
  return new Promise((resolve, reject) => {
    chrome.hid.getDevices({}, (hidDevices) => {
      // TODO This needs to be smarter about selecting a device
      if (hidDevices.length) {
        resolve(hidDevices[0]);
      } else {
        reject('no devices connected');
      }
    });
  });
````

You might need to build something similar to this to interface with your rust layer.

**Comment by CraigglesO** [comment]
This is great. Makes sense. So a javascript example, I can just pass in an npm `node-hid` to find the device.

I'm guessing the ChromeHidTransport goes much like this:

``` javascript
export class ChromeHidTransport extends Transport {
  constructor(deviceData) {
    super(deviceData);
  }

  _write(): Promise<any> {
    return new Promise();
  }

  _read(): Promise<any> {
    return new Promise();
  }
}
```

although the example is confusingly circular as the factory method is from device-client-manager.

Not to be too much of a pain, can you give me the ChromeHidTransport example? I think that's where all the magic happens! Would just save me a ton of time on this project.

**Comment by CraigglesO** [comment]
Update - I am really close of course. Just creating a factory works:

``` javascript
getActiveDeviceId()
  .then((device) => {
    console.log("device", device);
    return KeepKey.factory(new HidTransport(device))
  })
  .then((client) => {
    console.log("client", client);
  })
  .catch((err) => {
    console.log("Error", err);
  })

export class HidTransport extends Transport {
  constructor(deviceData) {
    super(deviceData);
  }

  _write(): Promise<any> {
    return new Promise((resolve, reject) => { resolve(this.write) });
  }

  _read(): Promise<any> {
    return new Promise((resolve, reject) => { resolve(this.read) });
  }
}

function getActiveDeviceId() {
  return new Promise((resolve, reject) => {
    let devices = HID.devices(11044, 1);
    if (devices.length) {
      resolve(devices[0]);
    }
  });
}
```


But obviously I am getting this error:
```
caught in client: TypeError: Cannot read property 'toArrayBuffer' of undefined
    at /Users/craigoconnor/Desktop/@parity:keepkey/device-client/dist/transport.js:97:63
    at tryCallOne (/Users/craigoconnor/Desktop/@parity:keepkey/device-client/node_modules/promise/lib/core.js:37:12)
    at /Users/craigoconnor/Desktop/@parity:keepkey/device-client/node_modules/promise/lib/core.js:123:15
    at flush (/Users/craigoconnor/Desktop/@parity:keepkey/device-client/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by keepkeyjon** [comment]
https://github.com/keepkey/electron-quick-start, which we just recently published, should be a good starting point.
